jobs:
  stage_0_job_0:
    name: image-pipeline perception
    runs-on: windows-2019
    strategy:
      fail-fast: false
    needs: []
    env:
      CONDA_BLD_PATH: C:\\bld\\
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        channels: conda-forge
        miniforge-variant: Mambaforge
        miniforge-version: latest
        use-mamba: 'true'
        channel-priority: 'true'
    - run: conda install -c conda-forge -n base --yes --quiet conda-build pip mamba
        ruamel.yaml anaconda-client
      name: Install conda-build, boa and activate environment
    - shell: cmd
      run: |
        set "CI=azure"
        call activate base

        :: 2 cores available on Appveyor workers: https://www.appveyor.com/docs/build-environment/#build-vm-configurations
        :: CPU_COUNT is passed through conda build: https://github.com/conda/conda-build/pull/1149
        set CPU_COUNT=2

        set PYTHONUNBUFFERED=1

        conda config --set show_channel_urls true
        conda config --set auto_update_conda false
        conda config --set add_pip_as_python_dependency false

        call setup_x64

        :: Set the conda-build working directory to a smaller path
        if "%CONDA_BLD_PATH%" == "" (
            set "CONDA_BLD_PATH=C:\\bld\\"
        )

        :: Remove some directories from PATH
        set "PATH=%PATH:C:\\ProgramData\\Chocolatey\\bin;=%"
        set "PATH=%PATH:C:\\Program Files (x86)\\sbt\\bin;=%"
        set "PATH=%PATH:C:\\Rust\\.cargo\\bin;=%"
        set "PATH=%PATH:C:\\Program Files\\Git\\usr\\bin;=%"
        set "PATH=%PATH:C:\\Program Files\\Git\\cmd;=%"
        set "PATH=%PATH:C:\\Program Files\\Git\\mingw64\\bin;=%"
        set "PATH=%PATH:C:\\Program Files (x86)\\Subversion\\bin;=%"
        set "PATH=%PATH:C:\\Program Files\\CMake\\bin;=%"
        set "PATH=%PATH:C:\\Program Files\\OpenSSL\\bin;=%"
        set "PATH=%PATH:C:\\Strawberry\\c\\bin;=%"
        set "PATH=%PATH:C:\\Strawberry\\perl\\bin;=%"
        set "PATH=%PATH:C:\\Strawberry\\perl\\site\\bin;=%"
        set "PATH=%PATH:c:\\tools\\php;=%"

        :: On azure, there are libcrypto*.dll & libssl*.dll under
        :: C:\\Windows\\System32, which should not be there (no vendor dlls in windows folder).
        :: They would be found before the openssl libs of the conda environment, so we delete them.
        if defined CI (
            DEL C:\\Windows\\System32\\libcrypto-1_1-x64.dll || (Echo Ignoring failure to delete C:\\Windows\\System32\\libcrypto-1_1-x64.dll)
            DEL C:\\Windows\\System32\\libssl-1_1-x64.dll || (Echo Ignoring failure to delete C:\\Windows\\System32\\libssl-1_1-x64.dll)
        )

        :: Make paths like C:\\hostedtoolcache\\windows\\Ruby\\2.5.7\\x64\\bin garbage
        set "PATH=%PATH:ostedtoolcache=%"

        mkdir "%CONDA%\\etc\\conda\\activate.d"

        echo set "CONDA_BLD_PATH=%CONDA_BLD_PATH%"         > "%CONDA%\\etc\\conda\\activate.d\\conda-forge-ci-setup-activate.bat"
        echo set "CPU_COUNT=%CPU_COUNT%"                  >> "%CONDA%\\etc\\conda\\activate.d\\conda-forge-ci-setup-activate.bat"
        echo set "PYTHONUNBUFFERED=%PYTHONUNBUFFERED%"    >> "%CONDA%\\etc\\conda\\activate.d\\conda-forge-ci-setup-activate.bat"
        echo set "PATH=%PATH%"                            >> "%CONDA%\\etc\\conda\\activate.d\\conda-forge-ci-setup-activate.bat"

        conda info
        conda config --show-sources
        conda list --show-channel-urls
      name: conda-forge build setup
    - shell: cmd
      run: |
        setlocal EnableExtensions EnableDelayedExpansion
        call %CONDA%\condabin\conda_hook.bat
        call %CONDA%\condabin\conda.bat activate base

        set "PATH=%PATH:C:\ProgramData\Chocolatey\bin;=%"
        set "PATH=%PATH:C:\Program Files (x86)\sbt\bin;=%"
        set "PATH=%PATH:C:\Rust\.cargo\bin;=%"
        set "PATH=%PATH:C:\Program Files\Git\usr\bin;=%"
        set "PATH=%PATH:C:\Program Files\Git\cmd;=%"
        set "PATH=%PATH:C:\Program Files\Git\mingw64\bin;=%"
        set "PATH=%PATH:C:\Program Files (x86)\Subversion\bin;=%"
        set "PATH=%PATH:C:\Program Files\CMake\bin;=%"
        set "PATH=%PATH:C:\Program Files\OpenSSL\bin;=%"
        set "PATH=%PATH:C:\Strawberry\c\bin;=%"
        set "PATH=%PATH:C:\Strawberry\perl\bin;=%"
        set "PATH=%PATH:C:\Strawberry\perl\site\bin;=%"
        set "PATH=%PATH:c:\tools\php;=%"
        :: Make paths like C:\\hostedtoolcache\\windows\\Ruby\\2.5.7\\x64\\bin garbage
        set "PATH=%PATH:ostedtoolcache=%"

        echo "PATH is %PATH%"
        echo "CONDA_BLD_PATH is %CONDA_BLD_PATH%"

        rmdir /Q/S C:\Strawberry\
        rmdir /Q/S "C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\"

        set "FEEDSTOCK_ROOT=%cd%"

        mkdir %CONDA_BLD_PATH%
        call conda index %CONDA_BLD_PATH%

        call conda config --remove channels defaults
        call conda config --add channels conda-forge
        call conda config --add channels robostack-humble
        call conda config --add channels %CONDA_BLD_PATH%
        :: call conda config --set channel_priority strict

        :: Enable long path names on Windows
        reg add HKLM\SYSTEM\CurrentControlSet\Control\FileSystem /v LongPathsEnabled /t REG_DWORD /d 1 /f

        :: conda remove --force m2-git

        :: C:\Miniconda\python.exe -m pip install git+https://github.com/mamba-org/boa.git@main
        call conda install boa
        if errorlevel 1 exit 1

        for %%X in (%CURRENT_RECIPES%) do (
            echo "BUILDING RECIPE %%X"
            cd %FEEDSTOCK_ROOT%\recipes\%%X\
            boa build . -m %FEEDSTOCK_ROOT%\.ci_support\conda_forge_pinnings.yaml -m %FEEDSTOCK_ROOT%\conda_build_config.yaml
            if errorlevel 1 exit 1
        )

        anaconda -t %ANACONDA_API_TOKEN% upload "C:\bld\win-64\*.tar.bz2" --force
        if errorlevel 1 exit 1
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-image-pipeline ros-humble-perception
        PYTHONUNBUFFERED: 1
      name: Build ros-humble-image-pipeline ros-humble-perception
on:
  push:
    branches:
    - buildbranch_win
